FROM golang:1.18.0 as base

RUN apt-get clean
RUN apt-get update && apt-get install -y ca-certificates git-core ssh zip && apt-get install --assume-yes awscli

ENV GO111MODULE=on
ENV GRPC_DNS_RESOLVER=native
ENV GOSUMDB=off
ENV GOPROXY=direct

ADD ./go.mod /app/go.mod

#adding ssh keys
ADD id_rsa /root/.ssh/id_rsa
RUN chmod 700 /root/.ssh/id_rsa

#setting git configs
RUN echo "Host github.com\n\tStrictHostKeyChecking no\n" >> /root/.ssh/config
RUN git config --global url."git@github.com:".insteadOf "https://github.com/"

ARG service_name=""
ENV SERVICE_NAME=$service_name

ARG track=""
ENV TRACK=$track

ARG version=""
ENV VERSION=$version

ARG lambda_destinations
ENV LAMBDA_DESTINATIONS=$lambda_destinations

WORKDIR /app/

#create vendor directory
RUN go mod download

ADD . /app/

RUN go mod vendor

#building source code
RUN GOOS=linux go build -mod=vendor -o /app/main /app/src/lambda_main.go

#removing ssh keys check if still required
RUN rm -f /root/.ssh/id_rsa
RUN rm -f /app/id_rsa

ADD src/config/config.yaml /app/config.yaml
ADD src/utils/loggerUtil/logger_config.yaml /app/logger_config.yaml

#adding docker entrypoint
COPY docker-entrypoint-lambda.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh
RUN bash /docker-entrypoint.sh