version: '3.7'

services:

  postgres:
    image: "postgres:10"
    restart: always
    hostname: postgres
    container_name: postgres
    # networks:
    #   - aws-localstack
    user: postgres
    ports:
      - "5432:5432"
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: book_db
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - "./docker/postgres.conf:/etc/postgresql/postgresql.conf"
    # healthcheck:
    #   test: [ "CMD", "pg_isready", "-h", "localhost" ]
    #   interval: 5s
    #   timeout: 10s
    #   retries: 3